export const unicodeEmojiCatalog = [
  { emoji: "😀", keywords: ["grinning", "happy", "smile"] },
  { emoji: "😃", keywords: ["happy", "smile", "joy"] },
  { emoji: "😄", keywords: ["joy", "laugh", "smile"] },
  { emoji: "😁", keywords: ["grin", "teeth", "happy"] },
  { emoji: "😆", keywords: ["laugh", "funny", "happy"] },
  { emoji: "😅", keywords: ["sweat", "relief", "laugh"] },
  { emoji: "🤣", keywords: ["rofl", "laugh", "funny"] },
  { emoji: "😂", keywords: ["laugh", "funny", "lol"] },
  { emoji: "🙂", keywords: ["smile", "calm", "nice"] },
  { emoji: "🙃", keywords: ["silly", "playful", "upside"] },
  { emoji: "😉", keywords: ["wink", "playful", "ok"] },
  { emoji: "😊", keywords: ["blush", "smile", "warm"] },
  { emoji: "😇", keywords: ["angel", "innocent", "good"] },
  { emoji: "🥰", keywords: ["love", "heart", "cute"] },
  { emoji: "😍", keywords: ["heart eyes", "love", "wow"] },
  { emoji: "🤩", keywords: ["star eyes", "awesome", "wow"] },
  { emoji: "😘", keywords: ["kiss", "love", "heart"] },
  { emoji: "😗", keywords: ["kiss", "cute", "lips"] },
  { emoji: "😚", keywords: ["kiss", "blush", "love"] },
  { emoji: "😙", keywords: ["kiss", "smile", "love"] },
  { emoji: "🥲", keywords: ["happy tears", "moved", "emotion"] },
  { emoji: "😋", keywords: ["yum", "tasty", "food"] },
  { emoji: "😛", keywords: ["tongue", "playful", "fun"] },
  { emoji: "😜", keywords: ["wink tongue", "silly", "fun"] },
  { emoji: "🤪", keywords: ["crazy", "wild", "fun"] },
  { emoji: "😝", keywords: ["tongue", "funny", "playful"] },
  { emoji: "🤑", keywords: ["money", "rich", "cash"] },
  { emoji: "🤗", keywords: ["hug", "thanks", "support"] },
  { emoji: "🤭", keywords: ["oops", "giggle", "surprised"] },
  { emoji: "🫢", keywords: ["shock", "surprise", "cover mouth"] },
  { emoji: "🫣", keywords: ["peek", "hide", "nervous"] },
  { emoji: "🤫", keywords: ["quiet", "secret", "shh"] },
  { emoji: "🤔", keywords: ["think", "question", "hmm"] },
  { emoji: "🫡", keywords: ["salute", "respect", "acknowledge"] },
  { emoji: "🤐", keywords: ["zip", "silent", "secret"] },
  { emoji: "🤨", keywords: ["skeptical", "doubt", "hmm"] },
  { emoji: "😐", keywords: ["neutral", "blank", "meh"] },
  { emoji: "😑", keywords: ["expressionless", "blank", "meh"] },
  { emoji: "😶", keywords: ["speechless", "quiet", "blank"] },
  { emoji: "🫥", keywords: ["dotted line", "disappear", "awkward"] },
  { emoji: "😶‍🌫️", keywords: ["in clouds", "confused", "foggy"] },
  { emoji: "😏", keywords: ["smirk", "confident", "playful"] },
  { emoji: "😒", keywords: ["unamused", "annoyed", "meh"] },
  { emoji: "🙄", keywords: ["eyeroll", "annoyed", "bored"] },
  { emoji: "😬", keywords: ["grimace", "awkward", "oops"] },
  { emoji: "😮‍💨", keywords: ["exhale", "relief", "tired"] },
  { emoji: "🤥", keywords: ["lie", "pinocchio", "fake"] },
  { emoji: "😌", keywords: ["relieved", "calm", "peace"] },
  { emoji: "😔", keywords: ["sad", "down", "upset"] },
  { emoji: "😪", keywords: ["sleepy", "tired", "sad"] },
  { emoji: "🤤", keywords: ["drool", "want", "hungry"] },
  { emoji: "😴", keywords: ["sleep", "tired", "night"] },
  { emoji: "😷", keywords: ["mask", "sick", "health"] },
  { emoji: "🤒", keywords: ["thermometer", "sick", "fever"] },
  { emoji: "🤕", keywords: ["bandage", "hurt", "injury"] },
  { emoji: "🤢", keywords: ["nausea", "sick", "gross"] },
  { emoji: "🤮", keywords: ["vomit", "sick", "gross"] },
  { emoji: "🤧", keywords: ["sneeze", "cold", "sick"] },
  { emoji: "🥵", keywords: ["hot", "heat", "warm"] },
  { emoji: "🥶", keywords: ["cold", "freeze", "ice"] },
  { emoji: "🥴", keywords: ["woozy", "confused", "dizzy"] },
  { emoji: "😵", keywords: ["dizzy", "dead", "shocked"] },
  { emoji: "🤯", keywords: ["mind blown", "shock", "wow"] },
  { emoji: "🤠", keywords: ["cowboy", "hat", "fun"] },
  { emoji: "🥳", keywords: ["party", "celebrate", "birthday"] },
  { emoji: "😎", keywords: ["cool", "sunglasses", "style"] },
  { emoji: "🤓", keywords: ["nerd", "smart", "geek"] },
  { emoji: "🧐", keywords: ["monocle", "inspect", "serious"] },
  { emoji: "😕", keywords: ["confused", "unsure", "sad"] },
  { emoji: "🫤", keywords: ["diagonal mouth", "unsure", "meh"] },
  { emoji: "😟", keywords: ["worried", "anxious", "sad"] },
  { emoji: "🙁", keywords: ["sad", "frown", "down"] },
  { emoji: "☹️", keywords: ["frown", "sad", "upset"] },
  { emoji: "😮", keywords: ["surprised", "wow", "shock"] },
  { emoji: "😯", keywords: ["hushed", "wow", "surprised"] },
  { emoji: "😲", keywords: ["astonished", "surprised", "shock"] },
  { emoji: "😳", keywords: ["flushed", "embarrassed", "shock"] },
  { emoji: "🥺", keywords: ["pleading", "cute", "please"] },
  { emoji: "🥹", keywords: ["tears", "moved", "emotional"] },
  { emoji: "😦", keywords: ["frown open", "worried", "shock"] },
  { emoji: "😧", keywords: ["anguish", "worried", "stress"] },
  { emoji: "😨", keywords: ["fear", "scared", "panic"] },
  { emoji: "😰", keywords: ["anxious", "sweat", "panic"] },
  { emoji: "😥", keywords: ["sad but relieved", "stress", "down"] },
  { emoji: "😢", keywords: ["cry", "sad", "tear"] },
  { emoji: "😭", keywords: ["sob", "cry", "tears"] },
  { emoji: "😱", keywords: ["scream", "shock", "fear"] },
  { emoji: "😖", keywords: ["confounded", "frustrated", "stress"] },
  { emoji: "😣", keywords: ["persevere", "struggle", "stress"] },
  { emoji: "😞", keywords: ["disappointed", "sad", "upset"] },
  { emoji: "😓", keywords: ["sweat", "hard work", "stress"] },
  { emoji: "😩", keywords: ["weary", "tired", "struggle"] },
  { emoji: "😫", keywords: ["tired", "exhausted", "stress"] },
  { emoji: "🥱", keywords: ["yawn", "sleepy", "tired"] },
  { emoji: "😤", keywords: ["triumph", "determined", "angry"] },
  { emoji: "😡", keywords: ["angry", "mad", "rage"] },
  { emoji: "😠", keywords: ["angry", "annoyed", "mad"] },
  { emoji: "🤬", keywords: ["swear", "rage", "angry"] },
  { emoji: "😈", keywords: ["devil", "mischief", "evil"] },
  { emoji: "👿", keywords: ["devil", "angry", "evil"] },
  { emoji: "💀", keywords: ["skull", "dead", "funny"] },
  { emoji: "☠️", keywords: ["danger", "poison", "skull"] },
  { emoji: "💩", keywords: ["poo", "funny", "mess"] },
  { emoji: "🤡", keywords: ["clown", "circus", "funny"] },
  { emoji: "👻", keywords: ["ghost", "spooky", "halloween"] },
  { emoji: "👽", keywords: ["alien", "space", "weird"] },
  { emoji: "🤖", keywords: ["robot", "ai", "bot"] },
  { emoji: "😺", keywords: ["cat", "happy", "pet"] },
  { emoji: "😸", keywords: ["cat grin", "pet", "happy"] },
  { emoji: "😹", keywords: ["cat tears", "funny", "pet"] },
  { emoji: "😻", keywords: ["cat heart eyes", "love", "pet"] },
  { emoji: "👍", keywords: ["thumbs up", "ok", "approve"] },
  { emoji: "👎", keywords: ["thumbs down", "reject", "no"] },
  { emoji: "👌", keywords: ["ok hand", "perfect", "approve"] },
  { emoji: "🤌", keywords: ["pinched fingers", "italian", "emphasis"] },
  { emoji: "🤏", keywords: ["small", "tiny", "little"] },
  { emoji: "✌️", keywords: ["peace", "victory", "two"] },
  { emoji: "🤞", keywords: ["hope", "luck", "crossed"] },
  { emoji: "🫰", keywords: ["finger heart", "love", "cute"] },
  { emoji: "🤟", keywords: ["love you", "hand", "sign"] },
  { emoji: "🤘", keywords: ["rock", "metal", "hand"] },
  { emoji: "🤙", keywords: ["call me", "phone", "hang loose"] },
  { emoji: "👈", keywords: ["left", "point", "direction"] },
  { emoji: "👉", keywords: ["right", "point", "direction"] },
  { emoji: "👆", keywords: ["up", "point", "direction"] },
  { emoji: "👇", keywords: ["down", "point", "direction"] },
  { emoji: "☝️", keywords: ["index up", "point", "one"] },
  { emoji: "✋", keywords: ["stop", "hand", "raise"] },
  { emoji: "🤚", keywords: ["raised back hand", "stop", "hand"] },
  { emoji: "🖐️", keywords: ["hand", "five", "high five"] },
  { emoji: "🖖", keywords: ["vulcan", "star trek", "hand"] },
  { emoji: "👋", keywords: ["wave", "hello", "bye"] },
  { emoji: "🤝", keywords: ["handshake", "deal", "team"] },
  { emoji: "🙏", keywords: ["pray", "thanks", "please"] },
  { emoji: "💪", keywords: ["muscle", "strong", "power"] },
  { emoji: "🦾", keywords: ["mechanical arm", "strong", "robot"] },
  { emoji: "🫶", keywords: ["heart hands", "love", "care"] },
  { emoji: "🙌", keywords: ["celebrate", "raise hands", "success"] },
  { emoji: "👏", keywords: ["clap", "great", "applause"] },
  { emoji: "🤲", keywords: ["open hands", "offer", "care"] },
  { emoji: "👐", keywords: ["open hands", "hug", "care"] },
  { emoji: "🫳", keywords: ["palm down", "drop", "hand"] },
  { emoji: "🫴", keywords: ["palm up", "offer", "hand"] },
  { emoji: "🔥", keywords: ["fire", "hot", "trending"] },
  { emoji: "✨", keywords: ["sparkles", "new", "shine"] },
  { emoji: "⚡", keywords: ["lightning", "fast", "power"] },
  { emoji: "💥", keywords: ["boom", "impact", "explosion"] },
  { emoji: "💫", keywords: ["dizzy", "stars", "sparkle"] },
  { emoji: "💯", keywords: ["hundred", "perfect", "great"] },
  { emoji: "✅", keywords: ["done", "approved", "check"] },
  { emoji: "❌", keywords: ["cancel", "wrong", "reject"] },
  { emoji: "❗", keywords: ["important", "alert", "warning"] },
  { emoji: "❓", keywords: ["question", "help", "ask"] },
  { emoji: "💡", keywords: ["idea", "tip", "think"] },
  { emoji: "🔍", keywords: ["search", "inspect", "find"] },
  { emoji: "🔒", keywords: ["lock", "secure", "privacy"] },
  { emoji: "🔓", keywords: ["unlock", "open", "access"] },
  { emoji: "📎", keywords: ["paperclip", "attach", "file"] },
  { emoji: "📌", keywords: ["pin", "save", "mark"] },
  { emoji: "📝", keywords: ["note", "write", "docs"] },
  { emoji: "📁", keywords: ["folder", "files", "project"] },
  { emoji: "📂", keywords: ["open folder", "files", "project"] },
  { emoji: "🗂️", keywords: ["card index", "organize", "project"] },
  { emoji: "🧾", keywords: ["receipt", "record", "docs"] },
  { emoji: "📦", keywords: ["package", "release", "box"] },
  { emoji: "📤", keywords: ["send", "upload", "share"] },
  { emoji: "📥", keywords: ["download", "receive", "inbox"] },
  { emoji: "📨", keywords: ["mail", "message", "send"] },
  { emoji: "💬", keywords: ["chat", "message", "talk"] },
  { emoji: "🗨️", keywords: ["speech", "talk", "message"] },
  { emoji: "🧠", keywords: ["brain", "think", "smart"] },
  { emoji: "👀", keywords: ["look", "see", "watch"] },
  { emoji: "📣", keywords: ["announce", "broadcast", "loud"] },
  { emoji: "🎉", keywords: ["celebrate", "party", "success"] },
  { emoji: "🎊", keywords: ["confetti", "party", "celebrate"] },
  { emoji: "🏆", keywords: ["trophy", "winner", "success"] },
  { emoji: "🥇", keywords: ["gold", "first", "winner"] },
  { emoji: "🚀", keywords: ["launch", "rocket", "ship"] },
  { emoji: "🛠️", keywords: ["build", "fix", "tools"] },
  { emoji: "⚙️", keywords: ["settings", "gear", "config"] },
  { emoji: "🧩", keywords: ["puzzle", "piece", "solve"] },
  { emoji: "🧪", keywords: ["test", "qa", "experiment"] },
  { emoji: "📈", keywords: ["growth", "analytics", "stats"] },
  { emoji: "📉", keywords: ["decline", "drop", "stats"] },
  { emoji: "🎯", keywords: ["target", "goal", "focus"] },
  { emoji: "🏁", keywords: ["finish", "goal", "race"] },
  { emoji: "🌟", keywords: ["star", "featured", "highlight"] },
  { emoji: "🌈", keywords: ["rainbow", "color", "happy"] },
  { emoji: "☕", keywords: ["coffee", "break", "work"] },
  { emoji: "🍕", keywords: ["pizza", "food", "party"] },
  { emoji: "🍔", keywords: ["burger", "food", "meal"] },
  { emoji: "🍀", keywords: ["luck", "clover", "good"] },
  { emoji: "📅", keywords: ["calendar", "schedule", "date"] },
  { emoji: "⏰", keywords: ["alarm", "time", "schedule"] },
  { emoji: "📡", keywords: ["signal", "broadcast", "network"] },
  { emoji: "🌐", keywords: ["globe", "world", "internet"] },
  { emoji: "💻", keywords: ["computer", "laptop", "work"] },
  { emoji: "🖥️", keywords: ["desktop", "monitor", "computer"] },
  { emoji: "⌨️", keywords: ["keyboard", "type", "computer"] },
  { emoji: "🖱️", keywords: ["mouse", "computer", "click"] },
  { emoji: "🧑‍💻", keywords: ["coder", "workspace", "developer"] },
  { emoji: "👨‍💻", keywords: ["developer", "man coder", "code"] },
  { emoji: "👩‍💻", keywords: ["developer", "woman coder", "code"] },
  { emoji: "📱", keywords: ["phone", "mobile", "device"] },
  { emoji: "🎧", keywords: ["audio", "headphones", "music"] },
  { emoji: "🎙️", keywords: ["microphone", "audio", "record"] },
];
