spring.application.name=platform
server.port=9090

# H2 Database settings
spring.datasource.url=jdbc:h2:mem:platformdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
app.base-url=http://localhost:9090
app.upload-dir=uploads
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
